// mutation-scope-pure.test.js — the decisions that GENERATE the mutation workflow's paths
// and the purity rule. Expectations are written OUT BY HAND: a test that read them back from
// the module would be mutated with it and stop seeing the mutant.
import { test } from 'vitest';
import assert from 'node:assert/strict';
import scope from '../src/mutation-scope-pure.js';

const open = '      # AUTO:mutation-scope — GENERATED by tools/mutation-scope.js from stryker.conf.json `mutate` and vitest.stryker.config.mjs `include`. NEVER edit by hand: node tools/mutation-scope.js --write';
const close = '      # /AUTO:mutation-scope';

test('workflowBlock: modules, then suites, then the models, then the config — each quoted, between markers', () => {
  assert.equal(scope.workflowBlock(['src/a.js'], ['test/a.test.js']), [
    open,
    "      - 'src/a.js'",
    "      - 'test/a.test.js'",
    "      - 'src/language-spec.js'",
    "      - 'src/cadence-spec.js'",
    "      - 'stryker.conf.json'",
    "      - 'vitest.stryker.config.mjs'",
    "      - 'package.json'",
    "      - 'package-lock.json'",
    "      - '.github/workflows/mutation.yml'",
    close,
  ].join('\n'));
});

test('spliceWorkflow: only the marked block changes, everything around it is kept byte for byte', () => {
  const before = `on:\n  push:\n    paths:\n${open}\n      - 'old.js'\n${close}\n  pull_request:\n`;
  assert.equal(scope.spliceWorkflow(before, `${open}\nNEW\n${close}`), `on:\n  push:\n    paths:\n${open}\nNEW\n${close}\n  pull_request:\n`);
});

test('spliceWorkflow: a block at the very START of the text is still found', () => {
  assert.equal(scope.spliceWorkflow(`${open}\nold\n${close}\ntail`, 'NEW'), 'NEW\ntail');
});

test('spliceWorkflow: missing or inverted markers are a NAMED REFUSAL, never a guess', () => {
  assert.throws(() => scope.spliceWorkflow('no markers here', 'x'), /markers are missing/);
  assert.throws(() => scope.spliceWorkflow(`${close}\n${open}`, 'x'), /markers are missing/);
  assert.throws(() => scope.spliceWorkflow(`${open} only`, 'x'), /markers are missing/);
  assert.throws(() => scope.spliceWorkflow(`head\n${close} only`, 'x'), /markers are missing/);
});

test('purityRule: every mutated module except the WRITTEN exemptions, dots escaped, fs/path/child_process refused', () => {
  const rule = scope.purityRule(['src/a.js', 'src/b-pure.js', 'src/k.js'], { 'src/k.js': 'reason' });
  assert.equal(rule.name, 'mutated-modules-must-stay-pure');
  assert.equal(rule.severity, 'error');
  // The comment is how a reader of .dependency-cruiser.json finds where exemptions live.
  assert.match(rule.comment, /GENERATED by tools\/mutation-scope\.js/);
  assert.match(rule.comment, /purityExemptions\(\) of src\/mutation-scope-pure\.js/);
  assert.equal(rule.from.path, '^(src/a\\.js|src/b-pure\\.js)$');
  assert.deepEqual(rule.to, { path: '^(fs|path|child_process)$', dependencyTypes: ['core'] });
  assert.ok(new RegExp(rule.from.path).test('src/a.js'));
  assert.ok(!new RegExp(rule.from.path).test('src/aXjs'), 'an unescaped dot would match any character');
  assert.ok(!new RegExp(rule.from.path).test('src/k.js'), 'an exempted module must stay outside the rule');
});

test('purityExemptions: kernel-endpoint is the one written exemption, with its reason', () => {
  const exempt = scope.purityExemptions();
  assert.deepEqual(Object.keys(exempt), ['src/kernel-endpoint.js']);
  assert.ok(exempt['src/kernel-endpoint.js'].length > 60, 'an exemption carries a real reason');
});

test('dormantExemptions: an exemption for a module no longer mutated is reported', () => {
  assert.deepEqual(scope.dormantExemptions(['src/a.js'], { 'src/a.js': 'r', 'src/gone.js': 'r' }), ['src/gone.js']);
  assert.deepEqual(scope.dormantExemptions(['src/a.js'], {}), []);
});

test('spliceRule: replaces the generated rule in place of the old one, keeps every other rule in order', () => {
  const cruiser = { options: { x: 1 }, forbidden: [{ name: 'a' }, { name: 'mutated-modules-must-stay-pure', old: true }, { name: 'b' }] };
  const out = scope.spliceRule(cruiser, { name: 'mutated-modules-must-stay-pure', fresh: true });
  assert.deepEqual(out.forbidden, [{ name: 'a' }, { name: 'b' }, { name: 'mutated-modules-must-stay-pure', fresh: true }]);
  assert.deepEqual(out.options, { x: 1 });
  assert.equal(cruiser.forbidden.length, 3, 'the input is never mutated');
});

test('configFiles and modelFiles: the non-module inputs of a mutation score', () => {
  assert.deepEqual(scope.configFiles(), ['stryker.conf.json', 'vitest.stryker.config.mjs', 'package.json', 'package-lock.json', '.github/workflows/mutation.yml']);
  assert.deepEqual(scope.modelFiles(), ['src/language-spec.js', 'src/cadence-spec.js']);
});
