#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// THE SPEC GATE — `npm run spec:tlc`.
//
// It runs EVERY entry of `runs.json` through TLC and demands the EXACT verdict
// declared there. The matrix is a SINGLE SOURCE: the `.cfg` files are GENERATED
// from it, never hand-maintained, so a constant can never drift between the
// declaration and what TLC actually checked.
//
// 🛑 THE GATE IS TWO-WAY, AND THAT IS THE WHOLE POINT.
//    A run expected GREEN that turns red = a real regression of the transport.
//    A run expected RED that turns green = either a sabotage that stopped
//    biting (spec gone hollow — the worst failure mode of a formal spec, a
//    GREEN that sees nothing) or a known defect that was FIXED, in which case
//    the check must MOVE into the baseline. Both need a human decision, so both
//    fail the gate LOUDLY. NEVER "repair" a red by editing `expect`.
//
// 🛑 NEVER delete the sabotage runs, the anti-vacuity runs or the rotation run.
//    They are what proves the spec means something.
//
// tla2tools.jar: downloaded on first run (pinned release + SHA-256 verified),
// NEVER committed. Java >= 8 required.
// ═══════════════════════════════════════════════════════════════════════════
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.dirname(fileURLToPath(import.meta.url));
const JAR = path.join(DIR, "tla2tools.jar");
const JAR_URL = "https://github.com/tlaplus/tlaplus/releases/download/v1.7.4/tla2tools.jar";
// SHA-256 of release v1.7.4 (anti supply-chain pin — bump ONLY deliberately).
const JAR_SHA256 = "936a262061c914694dfd669a543be24573c45d5aa0ff20a8b96b23d01e050e88";
const MODULE = "Transport";

const matrix = JSON.parse(readFileSync(path.join(DIR, "runs.json"), "utf8"));

function fail(msg) {
  console.error(`[spec-gate] FAIL ${msg}`);
  process.exit(1);
}

async function ensureJar() {
  const ok = () => createHash("sha256").update(readFileSync(JAR)).digest("hex") === JAR_SHA256;
  if (existsSync(JAR) && ok()) return;
  console.log(`[spec-gate] downloading ${JAR_URL} ...`);
  const res = await fetch(JAR_URL, { redirect: "follow" });
  if (!res.ok) throw new Error(`download jar: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const sha = createHash("sha256").update(buf).digest("hex");
  if (sha !== JAR_SHA256) throw new Error(`SHA-256 mismatch tla2tools.jar: ${sha} (expected ${JAR_SHA256})`);
  writeFileSync(JAR, buf);
}

// The `.cfg` is DERIVED from the matrix — a hand-written cfg is how a run ends
// up checking something other than what it claims.
function writeCfg(run) {
  const consts = { ...matrix.constantsDefault, ...(run.constants || {}) };
  const invs = (run.invariants || []).flatMap((n) => (n === "#shipped" ? matrix.shippedInvariants : [n]));
  const lines = [
    `\\* GENERATED by run-tlc.mjs from runs.json — DO NOT EDIT BY HAND.`,
    `\\* ${run.why}`,
    "CONSTANTS",
    ...Object.entries(consts).map(([k, v]) => `  ${k} = ${v}`),
    "SPECIFICATION Spec",
    ...invs.map((i) => `INVARIANT ${i}`),
    ...(run.properties || []).map((p) => `PROPERTY ${p}`),
    "",
  ];
  writeFileSync(path.join(DIR, `${run.cfg}.cfg`), lines.join("\n"));
  return { invs, props: run.properties || [] };
}

// 🔴 `-metadir` IS NOT AN OPTIMISATION, IT CLOSES A FLAKY — MEASURED IN CI ON
//    2026-08-20. Left to itself TLC names its scratch directory from the CURRENT
//    TIME **to the second** (`states/26-08-20-17-04-50`). We run eleven checks in
//    a row; on a fast enough machine two of them START IN THE SAME SECOND, the
//    second one hits `TLCRuntimeException: that directory already exists` and dies
//    WITHOUT naming any invariant. The gate then read "red on null" and reported a
//    model drift — a false accusation against the spec, produced by a clock.
// 🛑 TLC's own message is the confession: *"Trying to run TLC again will probably
//    fix this problem."* A tool that tells you to retry is a tool whose result
//    depends on when you asked. We do not retry: we REMOVE the ambiguity, by
//    naming the directory ourselves after the thing that is already unique — the
//    configuration. Option documented in the INSTALLED version (`-help`):
//    "specify the directory in which to store metadata; defaults to
//    SPEC-directory/states if not specified".
// ⚠️ SECOND EFFECT, deliberate: the per-run directory is now STABLE, so a run
//    OVERWRITES its predecessor instead of stacking one timestamped folder per
//    execution. That is what had quietly produced 464 files / 3.9 MB of scratch —
//    an unbounded writer, which the space doctrine forbids by construction.
function runTlc(cfg) {
  const r = spawnSync("java", ["-cp", JAR, "tlc2.TLC", "-deadlock", "-metadir", path.join("states", cfg), "-config", `${cfg}.cfg`, `${MODULE}.tla`], {
    cwd: DIR,
    encoding: "utf8",
    timeout: 600_000,
  });
  const out = (r.stdout || "") + (r.stderr || "");
  return { out, green: /Model checking completed\. No error has been found/.test(out) };
}

// A property violation and an invariant violation are announced differently by
// TLC. Reading only one of the two shapes would let half the expected reds pass
// as "some other error" — that is a gate that certifies instead of protecting.
// ⚠️ TLC NAMES a violated INVARIANT and does NOT name a violated TEMPORAL
//    property — it only says "Temporal properties were violated." Guessing a
//    name out of the counter-example text is how a gate ends up accepting the
//    wrong red (measured while writing this: a stray `"start"` was captured and
//    passed for a property name). So: a temporal red is attributed ONLY when
//    the run declares EXACTLY ONE property. Two or more ⇒ AMBIGUOUS, and the
//    gate says so instead of picking one.
function violationOf(out, props) {
  const inv = out.match(/(?:Invariant|Property) (\w+) is violated/);
  if (inv) return inv[1];
  if (/Temporal properties were violated/.test(out)) {
    return props.length === 1 ? props[0] : "AMBIGUOUS_TEMPORAL";
  }
  return null;
}

await ensureJar();

if (matrix.runs.length === 0) fail("runs.json declares NO run — an empty gate is a green that sees nothing.");

let checked = 0;
for (const run of matrix.runs) {
  const { invs, props } = writeCfg(run);
  if (invs.length + props.length === 0) fail(`${run.cfg}: checks nothing at all.`);
  const { out, green } = runTlc(run.cfg);
  const violated = violationOf(out, props);

  if (run.expect.green) {
    if (!green) fail(`${run.cfg} MUST be green — TLC reported "${violated || "an error"}":\n${out.slice(-2500)}`);
    console.log(`[spec-gate] OK  ${run.cfg} green  (${invs.concat(props).join(", ")})`);
  } else {
    const want = run.expect.violated;
    if (green) {
      fail(
        `${run.cfg} is GREEN but MUST violate ${want}.\n` +
          `  Either the spec stopped biting (hollow spec), or the engine changed and this\n` +
          `  check now belongs in the baseline. Decide it — do NOT edit runs.json to hide it.`
      );
    }
    if (violated !== want) {
      fail(`${run.cfg} is red on "${violated}" but MUST be red on "${want}" — the model drifted:\n${out.slice(-2500)}`);
    }
    console.log(`[spec-gate] OK  ${run.cfg} red on ${want}`);
  }
  checked += 1;
}

console.log(`[spec-gate] OK  ${checked}/${matrix.runs.length} TLC verdicts as declared`);
